title: "ICSGET 2025"
email: icsget@vardhaman.org
timezone: IST
baseurl: "/temp"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Ravivarman
paginate: 30
disqus: 'vardhaman'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
#ganalytics: UA-113961478-1

# Authors
authors:
  ravivarman:
    name: Ravivarman
    display_name: Ravivarman
    avatar: 'assets/images/sal.png'
    email: ravivarman@vardhaman.org
    web: https://www.sravivarman.com/
    twitter: https://twitter.com/
    description: "Dr. S. Ravivarman, Professor, EEE, Vardhaman College of Engineering, Hyderabad - 50128, Telangana, India."
# Social
# social:
#  instagram: https://www.instagram.com/#
#  facebook: https://www.facebook.com/#
#  twitter: https://twitter.com/#
#  linkedin: https://in.linkedin.com/school/vardhaman/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives